version: '3'
services:
  api:
    build:
      context: .
      args:
        - secret=sandetechtips
    container_name: backend
    image: sande265/portfolio-backend
    env_file:
      - ./.env
    volumes:
      - .:/usr/app
      - /usr/app/node_modules
    ports:
      - 8000:8000
