version: '3.8'
services:
  logger:
    container_name: portfolio-backend
    volumes:
      - .:/app
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - 8000:8000
